[project]
name = "cnfc"
version = "0.14.0"
description = "A DIMACS CNF compiler"
authors = [{name = "Aaron Windsor", email = "aaron.windsor@gmail.com"}]
license = "Unlicense"
readme = "README.md"
requires-python = ">=3.9"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
